### ISSUE TITLE
`juju config minio secret-key` returns empty string

### ISSUE THREAD

**Issue by grobbie** [canonical/minio-operator#35]
The command currently returns an empty string but it shouldn't.

**Comment by Barteus** [comment]
This happens when the secrey key is generated by charm (default empty value). 
https://github.com/canonical/minio-operator/blob/2b77883c19d00d5a1666ae7f318b28e5ee55bf41/src/charm.py#L29
https://github.com/canonical/minio-operator/blob/2b77883c19d00d5a1666ae7f318b28e5ee55bf41/src/charm.py#L56

**Workaround**
When you set the value yourself this works ok. Use:
```
juju config minio secret-key="<more_the_8_char_string>"
```

**Comment by grobbie** [comment]
Indeed that looks broken, the logic should be assigning the generated secret key to `self.model.config["secret-key"]` as a default value in the `init` method, unless a value was already assigned by the administrator.

**Comment by ca-scribner** [comment]
I don't know if this is broken or by intent.  I think the idea is that if no password is set at deployment, the default password is randomly generated and then stored somewhere the charm can access again (so it isn't making a new random value every time a hook fires).  @grobbie would your preference be that the charm write the random value it comes up with to it's own config so that you the user could later access it?

I don't know config is writable from the charm, but easy enough to try.

**Comment by DomFleischmann** [comment]
Config is not writable from the charm code, the only way we can return the auto generated password would be through an action or accessing the k8s secret.

**Comment by ca-scribner** [comment]
Closing as this will not be implemented.  If you need to reuse the password outside of the charm, for now the recommendation is to set the password yourself via config (`juju config charmname secret-key=xxx`) and then you can use it however you like (including pull it back out again with `juju config`)
